### ISSUE TITLE
在centos中 扫描 提示不在同一网络

### ISSUE THREAD

**Issue by wuweijie007** [B1ue1nWh1te/SeaBot_QQ#2]
你好，想问下，我用了一个新注册的qq作为测试扫描，在经过您的步骤启动image后，扫描提示 不在同一网络，有没有什么办法可以解决？
我采用了本地扫描后上传device.json的方式，但不起作用（centos是国外的服务器）

**Comment by B1ue1nWh1te** [comment]
emm..这个情况我没有遇到过 按理说没改端口这些的话应该是可以跑起来的 你也许可以去官网文档看看
